FROM node:22.14.0-bookworm-slim AS deps

WORKDIR /usr/app/src

RUN npm install -g npm@11.3.0
RUN npm install -g @bufbuild/buf @bufbuild/protoc-gen-es && \
    npm install -g @connectrpc/connect @bufbuild/protobuf

COPY buf.gen.yaml .

CMD ["npx", "buf", "generate"]
