//
//Copyright The Kubernetes Authors.
//
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.

// This file was autogenerated by go-to-protobuf. Do not edit it manually!

// @generated by protoc-gen-es v2.2.5 with parameter "target=ts,import_extension=.ts"
// @generated from file k8s.io/apimachinery/pkg/apis/meta/v1beta1/generated.proto (package k8s.io.apimachinery.pkg.apis.meta.v1beta1, syntax proto2)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { ListMeta, PartialObjectMetadata } from "../v1/generated_pb.ts";
import { file_k8s_io_apimachinery_pkg_apis_meta_v1_generated } from "../v1/generated_pb.ts";
import { file_k8s_io_apimachinery_pkg_runtime_schema_generated } from "../../../runtime/schema/generated_pb.ts";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file k8s.io/apimachinery/pkg/apis/meta/v1beta1/generated.proto.
 */
export const file_k8s_io_apimachinery_pkg_apis_meta_v1beta1_generated: GenFile = /*@__PURE__*/
  fileDesc("CjlrOHMuaW8vYXBpbWFjaGluZXJ5L3BrZy9hcGlzL21ldGEvdjFiZXRhMS9nZW5lcmF0ZWQucHJvdG8SKWs4cy5pby5hcGltYWNoaW5lcnkucGtnLmFwaXMubWV0YS52MWJldGExIqkBChlQYXJ0aWFsT2JqZWN0TWV0YWRhdGFMaXN0EkAKCG1ldGFkYXRhGAIgASgLMi4uazhzLmlvLmFwaW1hY2hpbmVyeS5wa2cuYXBpcy5tZXRhLnYxLkxpc3RNZXRhEkoKBWl0ZW1zGAEgAygLMjsuazhzLmlvLmFwaW1hY2hpbmVyeS5wa2cuYXBpcy5tZXRhLnYxLlBhcnRpYWxPYmplY3RNZXRhZGF0YUIrWilrOHMuaW8vYXBpbWFjaGluZXJ5L3BrZy9hcGlzL21ldGEvdjFiZXRhMQ", [file_k8s_io_apimachinery_pkg_apis_meta_v1_generated, file_k8s_io_apimachinery_pkg_runtime_schema_generated]);

/**
 * PartialObjectMetadataList contains a list of objects containing only their metadata.
 * +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object
 *
 * @generated from message k8s.io.apimachinery.pkg.apis.meta.v1beta1.PartialObjectMetadataList
 */
export type PartialObjectMetadataList = Message<"k8s.io.apimachinery.pkg.apis.meta.v1beta1.PartialObjectMetadataList"> & {
  /**
   * Standard list metadata.
   * More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
   * +optional
   *
   * @generated from field: optional k8s.io.apimachinery.pkg.apis.meta.v1.ListMeta metadata = 2;
   */
  metadata?: ListMeta;

  /**
   * items contains each of the included items.
   *
   * @generated from field: repeated k8s.io.apimachinery.pkg.apis.meta.v1.PartialObjectMetadata items = 1;
   */
  items: PartialObjectMetadata[];
};

/**
 * Describes the message k8s.io.apimachinery.pkg.apis.meta.v1beta1.PartialObjectMetadataList.
 * Use `create(PartialObjectMetadataListSchema)` to create a new message.
 */
export const PartialObjectMetadataListSchema: GenMessage<PartialObjectMetadataList> = /*@__PURE__*/
  messageDesc(file_k8s_io_apimachinery_pkg_apis_meta_v1beta1_generated, 0);

