// @generated by protoc-gen-es v2.11.0 with parameter "target=ts,import_extension=.ts"
// @generated from file sk8l_custom.proto (package sk8l_custom, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file sk8l_custom.proto.
 */
export const file_sk8l_custom: GenFile = /*@__PURE__*/
  fileDesc("ChFzazhsX2N1c3RvbS5wcm90bxILc2s4bF9jdXN0b20ijgMKCUpvYlN0YXR1cxItCgpjb25kaXRpb25zGAEgAygLMhkuc2s4bF9jdXN0b20uSm9iQ29uZGl0aW9uEhEKCXN0YXJ0VGltZRgCIAEoCRIWCg5jb21wbGV0aW9uVGltZRgDIAEoCRIOCgZhY3RpdmUYBCABKAUSEQoJc3VjY2VlZGVkGAUgASgFEg4KBmZhaWxlZBgGIAEoBRITCgt0ZXJtaW5hdGluZxgLIAEoBRIYChBjb21wbGV0ZWRJbmRleGVzGAcgASgJEhUKDWZhaWxlZEluZGV4ZXMYCiABKAkSRQoXdW5jb3VudGVkVGVybWluYXRlZFBvZHMYCCABKAsyJC5zazhsX2N1c3RvbS5VbmNvdW50ZWRUZXJtaW5hdGVkUG9kcxINCgVyZWFkeRgJIAEoBRImCgxzdGFydFRpbWVJblMY8AYgASgDUg9zdGFydF90aW1lX2luX3MSMAoRY29tcGxldGlvblRpbWVJblMY8QYgASgDUhRjb21wbGV0aW9uX3RpbWVfaW5fcyKnAQoMSm9iQ29uZGl0aW9uEgwKBHR5cGUYASABKAkSDgoGc3RhdHVzGAIgASgJEiYKDWxhc3RQcm9iZVRpbWUYAyABKAlSD2xhc3RfcHJvYmVfdGltZRIwChJsYXN0VHJhbnNpdGlvblRpbWUYBCABKAlSFGxhc3RfdHJhbnNpdGlvbl90aW1lEg4KBnJlYXNvbhgFIAEoCRIPCgdtZXNzYWdlGAYgASgJIjwKF1VuY291bnRlZFRlcm1pbmF0ZWRQb2RzEhEKCXN1Y2NlZWRlZBgBIAMoCRIOCgZmYWlsZWQYAiADKAliBnByb3RvMw");

/**
 * JobStatus represents the current state of a Job.
 *
 * @generated from message sk8l_custom.JobStatus
 */
export type JobStatus = Message<"sk8l_custom.JobStatus"> & {
  /**
   * The latest available observations of an object's current state. When a Job
   * fails, one of the conditions will have type "Failed" and status true. When
   * a Job is suspended, one of the conditions will have type "Suspended" and
   * status true; when the Job is resumed, the status of this condition will
   * become false. When a Job is completed, one of the conditions will have
   * type "Complete" and status true.
   * More info: https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/
   * +optional
   * +patchMergeKey=type
   * +patchStrategy=merge
   * +listType=atomic
   *
   * @generated from field: repeated sk8l_custom.JobCondition conditions = 1;
   */
  conditions: JobCondition[];

  /**
   * Represents time when the job controller started processing a job. When a
   * Job is created in the suspended state, this field is not set until the
   * first time it is resumed. This field is reset every time a Job is resumed
   * from suspension. It is represented in RFC3339 form and is in UTC.
   * +optional
   *
   * @generated from field: string startTime = 2;
   */
  startTime: string;

  /**
   * Represents time when the job was completed. It is not guaranteed to
   * be set in happens-before order across separate operations.
   * It is represented in RFC3339 form and is in UTC.
   * The completion time is only set when the job finishes successfully.
   * +optional
   *
   * @generated from field: string completionTime = 3;
   */
  completionTime: string;

  /**
   * The number of pending and running pods.
   * +optional
   *
   * @generated from field: int32 active = 4;
   */
  active: number;

  /**
   * The number of pods which reached phase Succeeded.
   * +optional
   *
   * @generated from field: int32 succeeded = 5;
   */
  succeeded: number;

  /**
   * The number of pods which reached phase Failed.
   * +optional
   *
   * @generated from field: int32 failed = 6;
   */
  failed: number;

  /**
   * The number of pods which are terminating (in phase Pending or Running
   * and have a deletionTimestamp).
   * This field is alpha-level. The job controller populates the field when
   * the feature gate JobPodReplacementPolicy is enabled (disabled by default).
   * +optional
   *
   * @generated from field: int32 terminating = 11;
   */
  terminating: number;

  /**
   * completedIndexes holds the completed indexes when .spec.completionMode =
   * "Indexed" in a text format. The indexes are represented as decimal integers
   * separated by commas. The numbers are listed in increasing order. Three or
   * more consecutive numbers are compressed and represented by the first and
   * last element of the series, separated by a hyphen.
   * For example, if the completed indexes are 1, 3, 4, 5 and 7, they are
   * represented as "1,3-5,7".
   * +optional
   *
   * @generated from field: string completedIndexes = 7;
   */
  completedIndexes: string;

  /**
   * FailedIndexes holds the failed indexes when backoffLimitPerIndex=true.
   * The indexes are represented in the text format analogous as for the
   * `completedIndexes` field, ie. they are kept as decimal integers
   * separated by commas. The numbers are listed in increasing order. Three or
   * more consecutive numbers are compressed and represented by the first and
   * last element of the series, separated by a hyphen.
   * For example, if the failed indexes are 1, 3, 4, 5 and 7, they are
   * represented as "1,3-5,7".
   * This field is alpha-level. It can be used when the `JobBackoffLimitPerIndex`
   * feature gate is enabled (disabled by default).
   * +optional
   *
   * @generated from field: string failedIndexes = 10;
   */
  failedIndexes: string;

  /**
   * uncountedTerminatedPods holds the UIDs of Pods that have terminated but
   * the job controller hasn't yet accounted for in the status counters.
   * Old jobs might not be tracked using this field, in which case the field
   * remains null.
   * +optional
   *
   * @generated from field: sk8l_custom.UncountedTerminatedPods uncountedTerminatedPods = 8;
   */
  uncountedTerminatedPods?: UncountedTerminatedPods;

  /**
   * The number of pods which have a Ready condition.
   * This field is beta-level. The job controller populates the field when
   * the feature gate JobReadyPods is enabled (enabled by default).
   * +optional
   *
   * @generated from field: int32 ready = 9;
   */
  ready: number;

  /**
   * ////// sk8l custom
   *
   * @generated from field: int64 startTimeInS = 880 [json_name = "start_time_in_s"];
   */
  startTimeInS: bigint;

  /**
   * @generated from field: int64 completionTimeInS = 881 [json_name = "completion_time_in_s"];
   */
  completionTimeInS: bigint;
};

/**
 * Describes the message sk8l_custom.JobStatus.
 * Use `create(JobStatusSchema)` to create a new message.
 */
export const JobStatusSchema: GenMessage<JobStatus> = /*@__PURE__*/
  messageDesc(file_sk8l_custom, 0);

/**
 * JobCondition describes current state of a job.
 *
 * @generated from message sk8l_custom.JobCondition
 */
export type JobCondition = Message<"sk8l_custom.JobCondition"> & {
  /**
   * @generated from field: string type = 1;
   */
  type: string;

  /**
   * @generated from field: string status = 2;
   */
  status: string;

  /**
   * @generated from field: string lastProbeTime = 3 [json_name = "last_probe_time"];
   */
  lastProbeTime: string;

  /**
   * @generated from field: string lastTransitionTime = 4 [json_name = "last_transition_time"];
   */
  lastTransitionTime: string;

  /**
   * @generated from field: string reason = 5;
   */
  reason: string;

  /**
   * @generated from field: string message = 6;
   */
  message: string;
};

/**
 * Describes the message sk8l_custom.JobCondition.
 * Use `create(JobConditionSchema)` to create a new message.
 */
export const JobConditionSchema: GenMessage<JobCondition> = /*@__PURE__*/
  messageDesc(file_sk8l_custom, 1);

/**
 * UncountedTerminatedPods holds UIDs of Pods that have terminated but haven't
 * been accounted in Job status counters.
 *
 * @generated from message sk8l_custom.UncountedTerminatedPods
 */
export type UncountedTerminatedPods = Message<"sk8l_custom.UncountedTerminatedPods"> & {
  /**
   * @generated from field: repeated string succeeded = 1;
   */
  succeeded: string[];

  /**
   * @generated from field: repeated string failed = 2;
   */
  failed: string[];
};

/**
 * Describes the message sk8l_custom.UncountedTerminatedPods.
 * Use `create(UncountedTerminatedPodsSchema)` to create a new message.
 */
export const UncountedTerminatedPodsSchema: GenMessage<UncountedTerminatedPods> = /*@__PURE__*/
  messageDesc(file_sk8l_custom, 2);

