name: k8s-rwkld

on:
  workflow_call:
    inputs:
      pull_request_number:
        required: true
        type: number
      image_tag:
        required: true
        type: string
      kind_version:
        required: true
        type: string
      k8s_version:
        required: true
        type: string
      k8s_image:
        required: true
        type: string
jobs:
  k8s-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Setup Kubernetes cluster ${{ inputs.kind_version }}/${{ inputs.k8s_version }}
        uses: engineerd/setup-kind@v0.5.0
        with:
          name: sk8l
          version: ${{ inputs.kind_version }}
          image: ${{ inputs.k8s_image }}
          config: testdata/sk8l-kind.yml
      - name: Test connection
        run: |
          kubectl cluster-info > /dev/null
          kubectl describe node > /dev/null
      - name: Install Helm
        uses: azure/setup-helm@v4.2.0
        with:
          version: 'v3.13.3'
      - name: Setup certs
        run: |
          make setup-certs > /dev/null
      - name: Install Chart
        run: |
          make install-chart-ci > /dev/null
      - name: ui smoke tests
        id: ui_smoke_tests
        run: |
          ./ci/ui_smoke_tests.sh
      - name: ui smoke tests error output
        if: ${{ failure() && steps.ui_smoke_tests.conclusion == 'failure' }}
        run: |
          echo "----------------------------"
          kubectl get pods -n sk8l
          kubectl get cronjobs -n sk8l
          echo "----------------------------"
          kubectl get jobs cypress-job -n sk8l
          kubectl logs job.batch/cypress-job -n sk8l
          echo "----------------------------"
          curl -vvv http://0.0.0.0:9901/clusters
          exit 1
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: e2e-job-ss
          path: cypress/sk8l.js/screenshots/
